spring:
  application:
    name: spring-ai-demo
  ai:
    # openai:
    #   api-key: your openai-api-key
    #   base-url: https://api.openai.com
    # google:
    #   genai:
    #     api-key: ${GOOGLE_GENAI_API_KEY}
    ollama:
      chat:
        # http http://localhost:11434/api/tags -b to see available models
        model: mistral:7b
        # model: deepseek-r1:1.5b
        options:
          temperature: 0.8
          # maxTokens: 1024
          # top-k: 5
          # top-p: 0.9
      init:
        pull-model-strategy: when-missing

management:
  endpoints:
    web:
      exposure:
        include: "*"
